### ISSUE TITLE
Near "(": syntax error with adding permissions to user groups

### ISSUE THREAD

**Issue by MISatPremier** [openrport/openrport#40] opened 2024-01-29 21:01 UTC
**Describe the bug**

"near "(": syntax error"
when trying to add tunnel or other permissions to any user groups

A feature request is not a bug. Feature requests are welcome. Follow [this link](https://github.com/realvnc-labs/rport/discussions/categories/roadmap-feature-wishes-ideas).

In case you know it. Is the bug related to `rportd` (server) or `rport` (client)?
rportd server

**Environment**
Describe the environment where the bug occurs:
the Web GUI, settings --> user groups --> editing any group permissions and adding any type of permissions results in the syntax error

* RPort version 0.9.14
* OS details (Linux distribution, and version or Windows version) Ubuntu 22.04.3
* Is rportd running inside a docker container? no
* Are you using a reverse proxy? If yes, which one? no

**Log file**
Before submitting a bug report, inspect the log files of client and server.
`/var/log/rport/rportd.log` for the server and `/var/log/rport/rport.log` or `C:\Program Files\rport\rport.log` for the client.
[Increase the log level to debug](https://github.com/realvnc-labs/rport/blob/0.9.0/rport.example.conf#L169-L171) and try to reproduce the error.
Include relevant lines into your report.

[rportd.log](https://github.com/openrport/openrport/files/14089535/rportd.log)

**Screenshots**

![Capture](https://github.com/openrport/openrport/assets/158099541/29639e2f-2ffa-47bc-b86f-dadcc53ed489)
![Capture2](https://github.com/openrport/openrport/assets/158099541/84e844e1-ce5b-486e-9574-f5ae0a4f0f2e)

**Additional context**
did a fresh install on a fresh server and had the same issue.

**Comment by MISatPremier** [comment] 2024-01-29 21:06
this specifically caught my eye in the log file


2024/01/29 20:57:12.288 GET /api/v1/status 200 1ms 391B (192.168.1.246)
2024/01/29 20:57:12 error: api-listener: runtime error: invalid memory address or nil pointer dereference
2024/01/29 20:57:12 error: api-listener: goroutine 3737 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.19.13/x64/src/runtime/debug/stack.go:24 +0x65
github.com/gorilla/handlers.recoveryHandler.log({{0x1337840, 0xc000758460}, {0x1335820, 0xc000421140}, 0x1}, {0xc00117ace0?, 0xc000a193f8?, 0x46ac8e?})
	/home/runner/go/pkg/mod/github.com/gorilla/handlers@v1.5.1/recovery.go:89 +0x77
github.com/gorilla/handlers.recoveryHandler.ServeHTTP.func1()
	/home/runner/go/pkg/mod/github.com/gorilla/handlers@v1.5.1/recovery.go:74 +0xcb
panic({0xeafa80, 0x1a261c0})
	/opt/hostedtoolcache/go/1.19.13/x64/src/runtime/panic.go:884 +0x212
github.com/openrport/openrport/plus.(*ManagerProvider).getCap(0xc0004dca10?, {0x1039a30?, 0x55555555555555?})
	/home/runner/work/openrport/openrport/plus/manager.go:245 +0x39
github.com/openrport/openrport/plus.(*ManagerProvider).GetStatusCapabilityEx(0xd?)
	/home/runner/work/openrport/openrport/plus/manager.go:167 +0x25
github.com/openrport/openrport/server.(*APIListener).handlePlusStatus(0xc00044c9a0, {0x133c528, 0xc000fb06c0}, 0xd?)
	/home/runner/work/openrport/openrport/server/api_handler_plus.go:115 +0x6f
net/http.HandlerFunc.ServeHTTP(0xc0009f5100?, {0x133c528?, 0xc000fb06c0?}, 0x203000?)
	/opt/hostedtoolcache/go/1.19.13/x64/src/net/http/server.go:2109 +0x2f
github.com/openrport/openrport/share/security.RejectBannedIPs.func1.1({0x133c528, 0xc000fb06c0}, 0xc000a198f0?)
	/home/runner/work/openrport/openrport/share/security/middleware.go:21 +0xa7
net/http.HandlerFunc.ServeHTTP(0x203000?, {0x133c528?, 0xc000fb06c0?}, 0x0?)
	/opt/hostedtoolcache/go/1.19.13/x64/src/net/http/server.go:2109 +0x2f
github.com/gorilla/handlers.recoveryHandler.ServeHTTP({{0x1337840, 0xc000758460}, {0x1335820, 0xc000421140}, 0x1}, {0x133c528?, 0xc000fb06c0?}, 0x5?)
	/home/runner/go/pkg/mod/github.com/gorilla/handlers@v1.5.1/recovery.go:78 +0xe4
github.com/gorilla/handlers.CompressHandlerLevel.func1({0x133aa28?, 0xc000e5c980}, 0xc0009f5100)
	/home/runner/go/pkg/mod/github.com/gorilla/handlers@v1.5.1/compress.go:141 +0x670
net/http.HandlerFunc.ServeHTTP(0x133b958?, {0x133aa28?, 0xc000e5c980?}, 0xc00078c410?)
	/opt/hostedtoolcache/go/1.19.13/x64/src/net/http/server.go:2109 +0x2f
github.com/jpillora/requestlog.WrapWith.func1({0x133b958?, 0xc000fcc0f8?}, 0xc000a305d0?)
	/home/runner/go/pkg/mod/github.com/jpillora/requestlog@v1.0.0/wrap.go:80 +0x62
net/http.HandlerFunc.ServeHTTP(0xc0009f5000?, {0x133b958?, 0xc000fcc0f8?}, 0x409c8a?)
	/opt/hostedtoolcache/go/1.19.13/x64/src/net/http/server.go:2109 +0x2f
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0006e2180, {0x133b958, 0xc000fcc0f8}, 0xc0004d4800)
	/home/runner/go/pkg/mod/github.com/gorilla/mux@v1.8.1/mux.go:212 +0x1cf
net/http.serverHandler.ServeHTTP({0xf36c60?}, {0x133b958, 0xc000fcc0f8}, 0xc0004d4800)
	/opt/hostedtoolcache/go/1.19.13/x64/src/net/http/server.go:2947 +0x30c
net/http.initALPNRequest.ServeHTTP({{0x133d1a8?, 0xc000d92a50?}, 0xc000d4f500?, {0xc000151a40?}}, {0x133b958, 0xc000fcc0f8}, 0xc0004d4800)
	/opt/hostedtoolcache/go/1.19.13/x64/src/net/http/server.go:3556 +0x245
net/http.(*http2serverConn).runHandler(0xc00051c060?, 0xc000431fd0?, 0x55f206?, 0xc0010be090?)
	/opt/hostedtoolcache/go/1.19.13/x64/src/net/http/h2_bundle.go:5910 +0x78
created by net/http.(*http2serverConn).processHeaders
	/opt/hostedtoolcache/go/1.19.13/x64/src/net/http/h2_bundle.go:5645 +0x5b9

**Comment by alhdo** [comment] 2024-01-30 11:13
Thanks for reporting the issue. That is the log you get in the server when you are trying to do the operation right ?

**Comment by MISatPremier** [comment] 2024-01-31 17:23
Correct alhdo, this is the log on the server when I am trying to change the permissions of the user groups on the web gui of said server

**Comment by calhounpaul** [comment] 2024-02-05 15:50
I tried making the update via the API and the same error happened. Is it something about the database update that's failing?

**Comment by JamieMcH** [comment] 2024-02-05 20:20
This appears to be a duplicate of issue #28

**Comment by alhdo** [comment] 2024-02-07 14:38
Thanks @JamieMcH for pointing this. @calhounpaul check if that can be the solution. If it is i will include the fix in the next release.

**Comment by calhounpaul** [comment] 2024-02-08 22:58
It didn't work for both a fresh install and for the old rport server I migrated over. It looks like this was one of the areas VNC was trying to monetize before pulling the plug. The "/var/lib/rport/user-auth.db" table file reads zero bytes on the migrated server, and group_details is blank on the other server.

**Comment by alhdo** [comment] 2024-02-19 21:46
Hello @calhounpaul I look deeper into this. If you are using the front-end version 1.X from Rport you will get this error. If you want to use the api just send the basic data instead. I will attach and example of what works. 

`curl --request PUT \
  --url https://url.users.openrport.io/api/v1/user-groups/managers \
  --header 'Authorization: Basic XXXXX' \
  --header 'Content-Type: application/json' \
  --data '{"permissions":{"auditlog":false,"commands":true,"monitoring":true,"scheduler":true,"scripts":false,"tunnels":false,"uploads":false,"vault":false}}'` 
  
  Please let me know if that solve your problem.

**Comment by calhounpaul** [comment] 2024-03-06 19:20
@alhdo That fixed it on the backend. Thanks!

**Comment by alhdo** [comment] 2024-03-07 14:09
I will close the issue please come back if you have any problems. The OSS Front-end is on his way we will be able to add more features.

**Closed by alhdo** 2024-03-07 14:09 UTC
